### ISSUE TITLE
Add appropriate body tags into jinja templates. 

### ISSUE THREAD

**Issue by toonarmycaptain** [toonarmycaptain/probable_immunity#40]
NB This is accomplished using `{% block body %}{% endblock %}` in the templates.

**Comment by ry-v1** [comment]
@toonarmycaptain  can I take up this.

**Comment by toonarmycaptain** [comment]
@ry-v1 go for it :)

**Comment by ry-v1** [comment]
@toonarmycaptain - I have looked at the templates and they seem fine to me. Where do you want to add body tags and the reason behind adding the tags. Thanks

**Comment by toonarmycaptain** [comment]
Usually you have all the header content in the header, and the rest of the content in the body. I'm not 100% on HTML/CSS, except for that's the way it's normally done, but I believe when styling pages, making things accessible for screen readers etc, it's important.

**Comment by ry-v1** [comment]
I have made the changes in the template in the same pull request. Please review.

**Comment by toonarmycaptain** [comment]
Fixed in #41
